/*
  Setup script for MySQL Database.
*/


/*
  Cards Table to store unique users
*/
START TRANSACTION;
CREATE TABLE `cards` (
  `uid` bigint(20) NOT NULL,
  `name` varchar(40) NOT NULL DEFAULT 'No Name',
  `value` decimal(10,2) unsigned NOT NULL DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `cards`
  ADD PRIMARY KEY (`uid`);
COMMIT;



/*
  Alias Table for using multiple cards for one user
*/
START TRANSACTION;
CREATE TABLE `alias` (
  `card_id` bigint(20) NOT NULL,
  `uid` bigint(20) NOT NULL,
  `comment` varchar(30) NOT NULL
  PRIMARY KEY (`card_id`),
  CONSTRAINT `alias_ibfk_1` FOREIGN KEY (`uid`) REFERENCES `cards` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;

/*
  Machines Table - if using multiple machines with different authorization levels.
  You may use this for cnc, lasercutter, ...
*/
START TRANSACTION;
CREATE TABLE `machines` (
  `name` varchar(40) NOT NULL
  PRIMARY KEY (`name`);
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;

/*
  Rates for different prices associated with an authorization per person and machine
*/
START TRANSACTION;
CREATE TABLE `rates` (
  `rid` varchar(20) NOT NULL,
  `per_login` decimal(5,2) unsigned NOT NULL DEFAULT 0.00,
  `per_minute` decimal(5,2) unsigned NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`rid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;

/*
  Sessions table, mostly for documentation of the usage by a certain person.
  Entries are automatically generated by program.
*/
START TRANSACTION;
CREATE TABLE `sessions` (
  `bid` int(11) NOT NULL AUTO_INCREMENT,
  `uid` bigint(20) DEFAULT NULL,
  `machine` varchar(40) DEFAULT NULL,
  `start_time` int(11) NOT NULL DEFAULT 0,
  `end_time` int(11) DEFAULT NULL,
  `price` decimal(6,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`bid`),
  KEY `quicksel` (`uid`,`machine`,`start_time`),
  KEY `sessions_ibfk_1` (`machine`),
  KEY `sessions_ibfk_2` (`uid`),
  CONSTRAINT `sessions_ibfk_1` FOREIGN KEY (`machine`) REFERENCES `machines` (`name`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `sessions_ibfk_2` FOREIGN KEY (`uid`) REFERENCES `cards` (`uid`) ON DELETE SET NULL ON UPDATE CASCADE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;


/*
  Authorization Table to lookup if a user is allowed to use the machine.
*/
START TRANSACTION;
CREATE TABLE `authorization` (
  `uid` bigint(20) NOT NULL,
  `machine` varchar(40) NOT NULL,
  `rate` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`uid`,`machine`),
  CONSTRAINT `authorization_ibfk_1` FOREIGN KEY (`machine`) REFERENCES `machines` (`name`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `authorization_ibfk_2` FOREIGN KEY (`uid`) REFERENCES `cards` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `authorization_ibfk_3` FOREIGN KEY (`rate`) REFERENCES `rates` (`rid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;
