/*
  Setup script for MySQL Database.
*/


/*
  Cards Table to store unique users
*/
START TRANSACTION;
CREATE TABLE `cards` (
  `uid` bigint(20) NOT NULL,
  `name` varchar(40) NOT NULL DEFAULT 'No Name',
  `value` float(10,2) NOT NULL DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `cards`
  ADD PRIMARY KEY (`uid`);
COMMIT;



/*
  Alias Table for using multiple cards for one user
*/
START TRANSACTION;
CREATE TABLE `alias` (
  `card_id` bigint(20) NOT NULL,
  `uid` bigint(20) NOT NULL,
  `comment` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `alias`
  ADD PRIMARY KEY (`card_id`),
  ADD KEY `alias_ibfk_1` (`uid`);

ALTER TABLE `alias`
  ADD CONSTRAINT `alias_ibfk_1` FOREIGN KEY (`uid`) REFERENCES `cards` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;



/*
  Machines Table - if using multiple machines with different authorization levels.
  You may use this for cnc, lasercutter, ...
*/
START TRANSACTION;
CREATE TABLE `machines` (
  `name` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `machines`
  ADD PRIMARY KEY (`name`);
COMMIT;



/*
  Sessions table, mostly for documentation of the usage by a certain person.
  Entries are automatically generated by program.
*/
START TRANSACTION;
CREATE TABLE `sessions` (
  `bid` int(11),
  `uid` bigint(20) DEFAULT NULL,
  `machine` varchar(40) DEFAULT NULL,
  `start_time` int(11) NOT NULL DEFAULT '0',
  `end_time` int(11) DEFAULT NULL,
  `price` decimal(6,2) NOT NULL DEFAULT '0.0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `sessions`
  ADD PRIMARY KEY (`bid`),
  ADD KEY `quicksel` (`uid`, `machine`, `start_time`),
  ADD KEY `sessions_ibfk_1` (`machine`),
  ADD KEY `sessions_ibfk_2` (`uid`);

ALTER TABLE `sessions`
  MODIFY `bid` int(11) NOT NULL AUTO_INCREMENT;
  
ALTER TABLE `sessions`
  ADD CONSTRAINT `sessions_ibfk_1` FOREIGN KEY (`machine`) REFERENCES `machines` (`name`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `sessions_ibfk_2` FOREIGN KEY (`uid`) REFERENCES `cards` (`uid`) ON DELETE SET NULL ON UPDATE CASCADE;
COMMIT;


/*
  Authorization Table to lookup if a user is allowed to use the machine.
*/
START TRANSACTION;
CREATE TABLE `authorization` (
  `uid` bigint(20) NOT NULL,
  `machine` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `authorization`
  ADD PRIMARY KEY (`uid`,`machine`),
  ADD KEY `authorization_ibfk_1` (`machine`);
  
ALTER TABLE `authorization`
  ADD CONSTRAINT `authorization_ibfk_1` FOREIGN KEY (`machine`) REFERENCES `machines` (`name`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `authorization_ibfk_2` FOREIGN KEY (`uid`) REFERENCES `cards` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;